rvm:
  - 2.5.1
cache: bundler
sudo: required
group: edge

services: docker

install: bundle install
bundler_args: "--binstubs=$PWD/bin --jobs 3 --retry 3 --without development"

branches:
  only:
  - master

env:
  global:
    - KITCHEN_YAML=.kitchen.yml
    - INSTANCE=default-fedora

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y nmap

before_script:
 - sudo nmap -p- localhost
 - sudo iptables -S
 - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
 - docker run --privileged -d -p 4444:4444 -e PORT=4444 jpetazzo/dind

script:
#  - DOCKER_HOST="tcp://localhost:4444" KITCHEN_YAML=.kitchen.yml time bundle exec kitchen test ${INSTANCE} -l debug
  - time bundle exec kitchen test ${INSTANCE} -l debug

after_script: |
  sudo nmap -p- localhost
  sudo iptables -S
  docker --version ;
  docker ps -a ;
  docker network ls ;
  docker images ;
  /bin/bash -c "docker inspect `docker ps -a | grep default-fedora: | awk '{ print $1 }'`" ;
  ls -laR ~/.dokken
  cat .kitchen/logs/kitchen.log ;
  cat Gemfile.lock ;
