rvm:
  - 2.2.5
cache: bundler

sudo: required

services: docker

install: bundle install
bundler_args: "--binstubs=$PWD/bin --jobs 3 --retry 3"

env:
  matrix:
  - INSTANCE=setup-amazonlinux

before_script:
 - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )

script:
  - KITCHEN_YAML=.kitchen.yml time bundle exec kitchen test ${INSTANCE}

after_script:
  - docker --version
  - docker images
  - docker ps -a
  - cat .kitchen/logs/kitchen.log
  - cat Gemfile.lock
