rvm:
  - 2.4.1
cache: bundler

sudo: required
dist: trusty
group: edge

services: docker

install: bundle install
bundler_args: "--binstubs=$PWD/bin --jobs 3 --retry 3"

env:
  matrix:
  - INSTANCE=default-fedora

before_script:
 - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
 - docker run --privileged -d -p 4444:4444 -e PORT=4444 jpetazzo/dind
 
script:
  - DOCKER_HOST="tcp://localhost:4444" KITCHEN_YAML=.kitchen.yml time bundle exec kitchen test ${INSTANCE} -l debug
  - KITCHEN_YAML=.kitchen.yml time bundle exec kitchen test ${INSTANCE} -l debug
  
after_script: |
  docker --version ;
  docker ps -a ;
  docker network ls ;
  docker images ;
  /bin/bash -c "docker inspect `docker ps -a | grep default-fedora-latest: | awk '{ print $1 }'`" ;
  ls -laR ~/.dokken
  cat .kitchen/logs/kitchen.log ;
  cat Gemfile.lock ;
