---
name: linters

'on':
  pull_request:
  push:
    branches: [main]

jobs:
  mdl:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Run yaml Lint
        uses: actionshub/markdownlint@main

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Run yaml Lint
        uses: actionshub/yamllint@main

  chefstyle:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.7', '3.0', '3.1']
    name: Chefstyle on Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake style

  integration:
    runs-on: ubuntu-latest
    needs: [mdl, yamllint, chefstyle]
    name: Kitchen Verify
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true
      - name: Create & Validate containers
        run: |
          bundle exec bundle exec kitchen create hello
          bundle exec bundle exec kitchen test helloagain
          bundle exec bundle exec kitchen destroy hello
        env:
          CHEF_LICENSE: "accept-no-persist"

  integration-windows:
    runs-on: windows-2019
    needs: [mdl, yamllint, chefstyle]
    name: Verify Windows containers
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true
      - name: Create & Validate containers
        run: |
          bundle exec bundle exec kitchen test chocolatey
        env:
          CHEF_LICENSE: "accept-no-persist"
